name: Limit complexity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck 
    
    - name: static analysis
      run: cppcheck --suppress=missingIncludeSystem --check-config --force --enable=all --error-exitcode=1 .

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 6 -x"*/pubsub_opts.c" -x "./Device4/client.py"
