name: publisher

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: publish1 build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Device1\device.vcxproj /p:configuration=debug /p:platform=x64
    
    
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 30s
    
    - name: publish1 run
      run: (echo hello && echo gloves && echo caridac && echo N)| D:\a\sync-devices-s1b4\sync-devices-s1b4\Device1\x64\Debug\device.exe pub
      
    - name: publish2 build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Device2\device2.vcxproj /p:configuration=debug /p:platform=x64
        
    - name: publish2 run
      run: (echo hello && echo gloves && echo caridac && echo N)| D:\a\sync-devices-s1b4\sync-devices-s1b4\Device2\x64\Debug\device2.exe pub
   
    - name: publish3 build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Device3\device3.vcxproj /p:configuration=debug /p:platform=x64

    - name: publish3 run
      run: (echo hello && echo gloves && echo caridac && echo N)| D:\a\sync-devices-s1b4\sync-devices-s1b4\Device3\x64\Debug\device3.exe pub
