name: publisher

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: msbuild solution build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Device1\Device1.vcxproj /p:configuration=debug /p:platform=x64
      
    - name: publish
      run: |
        (echo henry && echo x-ray && echo cardiac && echo N)| D:\a\sync-devices-s1b4\sync-devices-s1b4\x64\Debug\Device1.exe pub
