name: publisher

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: msbuild solution build
      run: msbuild.exe D:\a\sync-devices-s1b4\sync-devices-s1b4\Device1\device.sln
      
    - name: publish
      run: (echo hello && echo gloves && echo caridac)| D:\a\sync-devices-s1b4\sync-devices-s1b4\Device1\x64\Debug\device.exe pub
          
