name: subscriber3

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: subscribe3 build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Device3\device3.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: subsribe3 run
      run: |
        .\Device3\x64\Debug\Device3.exe sub
      timeout-minutes:  1
