name: Testing

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: Test build
      run: msbuild D:\a\sync-devices-s1b4\sync-devices-s1b4\Testing\test.vcxproj /p:configuration=debug /p:platform=x64
      
    - name: Test Run
      run: D:\a\sync-devices-s1b4\sync-devices-s1b4\Testing\x64\debug\test.exe
  
    
